name: "Clean up old builds"
on: 
  # workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  # - cron: "*/15 * * * *" # every day at midnight
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Github User
        run: |
          git --version
          git config --global user.name 'shippo-feron-sb'
          git config --global user.email 'feron-storybook@shippo.com'
      - name: Set up SSH
        uses: pioug/la-cle@v1.1.0
        with:
          GH_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Cleanup old builds
        run: |
          git clone git@github.com:shippo-feron-sb/shippo-feron-sb.github.io.git
          cd shippo-feron-sb.github.io
          sh cleanup.sh
      
