name: "Clean up old builds"
on:
  schedule:
  - cron: "0 0 * * *" # every day at midnight
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old builds
        run: |
          git clone https://github.com/shippo-feron-sb/shippo-feron-sb.github.io.git
          cd shippo-feron-sb.github.io
          sh cleanup.sh
      